### ISSUE TITLE
Nice theme

### ISSUE THREAD

**Issue by seniorcoder72** [charles0830/charles0830.github.io#3]
I'm [@seniorcoder72](https://github.com/seniorcoder72)
I've seen your profile page amazing.

Can you kindly teach me how to build the page like [your profile page](https://github.com/charles0830/charles0830.github.io)?
I'll wait for you kind message.

**Comment by charles0830** [comment]
Thank you for your compliments.

It's not surprising, but it's hard for anyone but the brightest to build such a profile from scratch on their own.
But we live in a rich data base.
All profiles on GitHub are open code.
github.com/<username>/<username>/readme.md

The problem is how to select the pieces that are familiar to him and put them together from the limitless pile of trees.
This is what makes the difference and determines the quality of your creations.

However, complete copy-paste is not recommended. Repetition is death.
Also, turn your attention to the first screen. Either way, first impressions are important.
Finally, avoid repetitive pictures or sentences.

Thank you for looking at my poor experience.
Looking forward to more questions, feedback and exchanges of experiences.

Note: Thank you for giving me a star.

**Comment by seniorcoder72** [comment]
I know all github accounts have its profile repository, and every repository has its own readme.md file.
By the way, I want to know which sample or frameworks did you use for the first page of your profile such amazing?
I've noticed you used angular JS app, but it was bundled version built,
Can you share me your profile source code or your reference repository.
Kindly help me. Thanks.

**Comment by charles0830** [comment]
In the repo, click readme.md file.
![image](https://github.com/charles0830/charles0830.github.io/assets/128301504/57ef55c7-d3a5-429d-948f-7276a4976d30)
You will go to https://github.com/'username'/'username'/blob/main/README.md
![image](https://github.com/charles0830/charles0830.github.io/assets/128301504/c41cb4b5-3102-48ca-be89-fbf7eb954efc)
The defult is "Preview".
Click code, you can see code.
![image](https://github.com/charles0830/charles0830.github.io/assets/128301504/8ff3bbb4-d469-421a-9c3b-ae8d9b1c90eb)
![image](https://github.com/charles0830/charles0830.github.io/assets/128301504/b2b02b65-bc81-40c0-9f95-6a7acc4a4ad6)

If you want, I am able to access your computer by AnyDesk.
Thanks.

**Comment by seniorcoder72** [comment]
You misunderstood my words.
I know how to make readme.md file for my overview page.
I mean your github page was so amazing that I want to have source code of that.
I noticed that it is angular JS app, but it is not source code on your repository.
It was the version only for deployment.
So I ask for you share me your source code of you github page so that I can fork it.

**Comment by charles0830** [comment]
I am not sure what do you mean.
GitHub or Personal Website?

**Comment by seniorcoder72** [comment]
https://charles0830.github.io/
I mean the source code or reference repository of this site.

**Comment by charles0830** [comment]
Oh, I removed my site's source code.
But here is other way.
https://github.com/emmabostian/developer-portfolios
In here, mouse right click and click Inspect.
Find github.io tag.
You can see some good and open-source profile sites.
I think it was this https://jayantgoel001.github.io/
Look @jayantgoel001's repo. You can find source code.
:)

**Comment by charles0830** [comment]
It is working for you?
https://github.com/JayantGoel001/JayantGoel001.github.io
This is repo link.

**Comment by seniorcoder72** [comment]
Thanks very much.
I'll try it.

**Comment by charles0830** [comment]
Please let me know if you need any further support.
If not, don't forget to press the issue solved button.
Thanks,

**Comment by seniorcoder72** [comment]
Sure, thanks.
